### ISSUE TITLE
Use the native CSS content-script injection on Chrome

### ISSUE THREAD

**Issue by AdamBurgess** [xthexder/wide-github#14]
If you use this, you don't get the flash of the narrow github interface, which is a huge hassle to me when using your extension...

But, you can't disable the custom style on non-repository pages.

I personally find this to be fine.
Waiting half a second for the pages you visit 90% of the time (repositories) is more important than a 'better' experience on pages you view 10% of the time (user profiles and settings).
To me, that's an acceptable downside.

**Comment by xthexder** [comment]
Right now the extension is the way it is so that I can use the same file for both Firefox and Chrome extensions. I might spend some time to write a Makefile that assembles both, but that might have to wait until I have more time.

I personally use Firefox, so I hadn't really noticed the flashing (it only happens when the cache is busted), but it looks like it happens every page load on chrome. I'll see what I can do.

**Comment by AdamBurgess** [comment]
Man, thanks for this update.
Awesome stuff.
