### ISSUE TITLE
How to decrease min width?

### ISSUE THREAD

**Issue by ntc2** [xthexder/wide-github#22]
Hi, this is a feature request that is probably really just a question about to modify the script for my use case. I use 1680x1050 monitor with two vertical panes, each of size 840x1050. So, I'd like the min width of github to be at most 840 pixels. I tried changing the `min-width: 980px` lines in the script, but that didn't have any effect. I don't know much about CSS.

How can I change the CSS so that min width of GitHub is at most 840 pixels?

I'm using the script via GreaseMonkey in Firefox on Linux.

**Comment by joeytwiddle** [comment]
It might help to clarify if you could show a specific issue that this causes you. But I think I see what your problem is.

As you suggested, this is not a problem with this extension (which allows the content to expand) but rather a problem with Github (which does not contract the content when it should). I fear that the CSS in this extension is not really going to help with your task, reducing the width of the content.

----

Anyway, I did a little investigation.

Like you, I also find when loading a page 840px that the content is too wide (producing scrollbars).

![joey s google-chrome at 1 31 00 pm on sunday 17 june 2018](https://user-images.githubusercontent.com/911799/41505125-411a9e52-7234-11e8-8faf-ee785f8daa38.png)

But if I click on Device mode in Chrome
![enable_device_mode](https://user-images.githubusercontent.com/911799/41505135-608fbd6c-7234-11e8-8fe4-9b1d08834647.png)
then the content immediately scales to fit:
![joey s google-chrome at 1 31 39 pm on sunday 17 june 2018](https://user-images.githubusercontent.com/911799/41505139-7314ad94-7234-11e8-94b8-7e483be86bd3.png)
I don't know what is causing that. Curiously it keeps resizing, whatever resolution I enter (to the point that the text becomes unreadable).

However, if I keep "Responsive" device mode enabled, and reload the page, then I get a completely different page layout:
![joey s google-chrome at 1 38 14 pm on sunday 17 june 2018](https://user-images.githubusercontent.com/911799/41505145-954e0cd4-7234-11e8-8c06-e2eb23f2fbd3.png)

I think that layout is probably what you should be getting for an 840px display. I don't know why Github doesn't give you that normally. (Perhaps they are hinting you to expand your browser size.) But for your purposes, we might want to know: what is the difference with "Responsive device mode" and how can we get that working in your browser?

You may like to take this problem up [with github](https://github.com/holman/ama/issues/152#issuecomment-4173208) or discuss it [with other users](https://github.com/isaacs/github/issues).

**Comment by xthexder** [comment]
The current min-width is set by Github, and is not something this script touches. I imagine some things would break if you set the width lower without switching to a different layout like device mode.
I'm sure you could get this to work, but it might be more effort than just changing `980px` to `840px`.

**Comment by ntc2** [comment]
Thanks for looking into this. I'm not using the extension anymore, so I'll close this issue.
