### ISSUE TITLE
Maximum width to expand to

### ISSUE THREAD

**Issue by joeytwiddle** [xthexder/wide-github#36]
I have quite a wide monitor at work, so while I appreciate Github content appearing wider than default, I don't really want it to fill my entire monitor. (Except when diffing, in that case I do!)

So in my version I set the maximum width to 1500px. (Relevant commits: [1](https://github.com/joeytwiddle/code/commit/00f1da0) [2](https://github.com/joeytwiddle/code/commit/84bf491))

Would you like me to open a PR for that?

(No problem if not. I just thought I'd offer. Thanks for this script!)

**Comment by Martii** [comment]
@joeytwiddle 

> I don't really want it to fill my entire monitor.

Couldn't you just size your browser instead?

**Comment by joeytwiddle** [comment]
I could resize my browser, but I like the width for other sites, and for diffing on GitHub.

I chose 1500px because I want GitHub to be wider than the default, but by 1500px it starts to look uncomfortable to me. Your simulation is an extreme example of that!

Here is how my smaller display looks with and without Wide-GitHub (I zoomed to 80% to make these captures):

<img src="https://user-images.githubusercontent.com/911799/41509450-4942a2ee-7286-11e8-8be1-c5ec8a7a9928.png" width="200">

<img src="https://user-images.githubusercontent.com/911799/41509451-4980b2e6-7286-11e8-92c5-b4482fba2d07.png" width="200">

Since different people have a different preferred max, making it configurable would make it possible to satisfy everyone. But that would need some extra implementation for the userscript and the extension.

**Comment by Martii** [comment]
@joeytwiddle 
Well I didn't change the dpi like most of those screens/OS would do and I haven't looked into when GH uses `em`, or equivalent *(hence the the word simulation used which would look mostly acceptable on a single UHD or better screen(s))*....

However options would be interesting. As per #21, #29, and  https://github.com/xthexder/wide-github/pull/29#issuecomment-368346831 toggling can be an option. This may also affect review at the extension store. I don't use the extension per say but this projects description is:

> ... This plugin changes all github repository pages to be full width ...

Perhaps a logical `or` list:
1. "Fixed Wide(r) GitHub" would be a better description for what you are asking and keep the original functionality of this script.
2. Add options to modify that fact.

Misc note: There's always going to be one page that doesn't respect any consistent description because it's rendered on GH's side only.

**Comment by xthexder** [comment]
If you're using Greasemonkey or similar, it's pretty easy to modify a few of the `max-width: 100%` fields to your preference.
I don't really want to maintain multiple versions of this extension, so until I have a nice way of adding settings (for GH Enterprise, toggling, max-wdith, etc...) I'm going to keep this extension simple.
I like the minimal permissions for the Chrome extension, which is the main thing stopping me from adding a settings menu.
