### ISSUE TITLE
Comment buttons can't be clicked in a wide diff.

### ISSUE THREAD

**Issue by dinoboy197** [xthexder/wide-github#42]
Am using version 1.2.3.

![image](https://user-images.githubusercontent.com/631178/50602040-3f199f00-0e5a-11e9-9347-b38530102c6d.png)

Scrolling to the right does not show the buttons.

**Comment by Martii** [comment]
@dinoboy197 

> Comment buttons can't be clicked in a wide diff

Will need an actual url on what you mean my "diff" please.

> Am using version 1.2.3.

Stylus .css or .user.js ?

Ref:
* https://github.com/xthexder/wide-github/commit/3b35d5cdb5662aa38133f1efd4dfb2cb570dd372 **PASS**
* https://github.com/xthexder/wide-github/pull/39/files **PASS**

**Comment by dinoboy197** [comment]
Thanks for your quick reply. I had expected the comment box to show up with a horizontal scrollbar, but it turns out that I have to scroll vertically to the bottom of the file that is being commented on to access the horizontal scroll. When I use this horizontal scroll at the bottom, then scroll back up, the comment button does appear.

**Comment by xthexder** [comment]
I think this is still a valid issue, the buttons shouldn't be hidden.

Going to leave it open until I can take a look later today.

**Comment by xthexder** [comment]
It looks like with the current Github styling, this can only occur on PRs with lines wider that the window, and only on the Unified diff. Word wrap is turned on only for the Split diff, so the issue doesn't occur.

I don't want to turn word wrap on for the Unified view, since it can be useful for viewing certain files. There's not much else that can be done to fix this.
