### ISSUE TITLE
The script is interfering with the page view after anchor navigation

### ISSUE THREAD

**Issue by DKroot** [xthexder/wide-github#51]
When the script v1.4.1 is enabled it messes up with the page view after anchor navigation e.g on GitHub Wiki pages in MediaWiki format. Here is a test case:

https://github.com/NETESOLUTIONS/ERNIE/wiki/Setup-Runbook#Default_client_parameters

With script disabled: the page is navigated precisely to the anchor as expected.
With script enabled: the page is navigated 2-3 lines down from the anchor, hiding it from the view.

**Comment by xthexder** [comment]
Which browser / extension are you using? Does this happen for all window sizes / how wide is the window?

This seems like the stylesheets are being applied after the browser has scrolled to the anchor, which I would expect not to be an issue for the UserStyles or Chrome Extension versions, but might be possible on the UserScripts JS version (since the css is added after page load).

I haven't been able to reproduce this locally, so if you're still having issues, I'll need to know a bit more about your setup.

**Comment by DKroot** [comment]
It was Chrome on Mac. It looks like the issue went away: I can't reproduce it anymore.
