### ISSUE TITLE
Top bar is too left-aligned.

### ISSUE THREAD

**Issue by rokejulianlockhart** [xthexder/wide-github#77]
![image](https://user-images.githubusercontent.com/42837531/233711752-18065656-0c5d-4ac6-9e2d-cf1023f3973b.png)

It sometimes fixes itself temporarily.

**Comment by xthexder** [comment]
I'm assuming you are also using the Refined GitHub extension?
There was a conflict a while ago between these 2 extensions, and Refined GitHub has since changed their CSS, making the compatibility fix unnecessary.

This issue is resolved by https://github.com/xthexder/wide-github/pull/76, however the change hasn't been merged and released on the Chrome / Mozilla web stores yet.

**Comment by rokejulianlockhart** [comment]
@xthexder, I am.

**Comment by xthexder** [comment]
I went through and released the last few bug fixes. v1.5.2 should now be available on the Mozilla Addons site.
If you Check for Updates on the extensions page in Firefox, you should be able to try it out.

Also, I'd appreciate it if you updated your extension review :)
